openapi: 3.0.0
info:
  title: LGU Payment API
  description: API documentation for the LGU Payment System
  version: "1.0.0"
servers:
  - url: http://lgu-payment-api.test/
paths:
  /api-create-transactions:
    post:
      tags:
        - Transaction
      summary: Create a new transaction
      description: Initiates a new payment transaction and generates a QR code.
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - reference_number
                - name
                - amount
                - company
              properties:
                reference_number:
                  type: string
                  description: Unique reference number for the transaction
                name:
                  type: string
                  description: Name of the payor
                amount:
                  type: number
                  description: Transaction amount
                company:
                  type: string
                  description: Company name
                mobile_number:
                  type: string
                  description: Mobile number of the payor
                email:
                  type: string
                  description: Email address of the payor
                convience_fee:
                  type: number
                  description: Convenience fee
                services:
                  type: array
                  description: List of services for the transaction
                  items:
                    type: object
                    properties:
                      code:
                        type: string
                      description:
                        type: string
                      qty:
                        type: integer
                      amount:
                        type: number
      responses:
        '200':
          description: Transaction created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  status_code:
                    type: integer
                  response:
                    type: object
                    properties:
                      redirect_url:
                        type: string
                      create_at:
                        type: string
                        format: date-time
                      txn_ref:
                        type: string
        '400':
          description: Bad request (missing or invalid fields)
        '401':
          description: Missing or invalid API key
        '502':
          description: Failed to generate transaction from API

  /api-categories:
    get:
      tags:
        - Transaction
      summary: Get all categories
      description: Returns a list of all available categories.
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: List of categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        cat_code:
                          type: string
                        cat_category:
                          type: string
        '401':
          description: Missing or invalid API key

  /api-dotransac_checkref:
    get:
      tags:
        - Transaction
      summary: Check transaction by reference
      description: Returns transaction details for a given reference ID.
      parameters:
        - in: query
          name: ref_id
          schema:
            type: string
          required: true
          description: Transaction reference ID
      responses:
        '200':
          description: Transaction found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  ref_id:
                    type: string
                  name:
                    type: string
                  company:
                    type: string
                  mobile:
                    type: string
                  email:
                    type: string
                  sub_total:
                    type: number
                  conv_fee:
                    type: number
                  grand_total:
                    type: number
                  deparment:
                    type: string
                  status:
                    type: string
                  qr_url:
                    type: string
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        description:
                          type: string
                        qty:
                          type: integer
                        amount:
                          type: number
                        other_fees:
                          type: number
                        total:
                          type: number
        '400':
          description: Missing ref_id
        '404':
          description: Transaction not found

  /api-dotransac_postback:
    post:
      tags:
        - Transaction
      summary: Transaction postback callback
      description: Receives payment gateway callback for transaction status update.
      parameters:
        - in: query
          name: ref_id
          schema:
            type: string
          required: true
          description: Transaction reference ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                callback_status:
                  type: string
                  description: Status value from payment gateway
                callback_data:
                  type: array
                  items:
                    type: object
      responses:
        '200':
          description: Callback processed successfully or duplicate
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Missing ref_id or invalid JSON
        '404':
          description: Transaction not found

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  
tags:
  - name: Transaction
    description: Transaction-related endpoints
